### ISSUE TITLE
Switch out alert to toaster

### ISSUE THREAD

**Issue by AshminJayson** [marahim20/playlister#1]
Switch out invalid url dialog alert to toast

**Comment by marahim20** [comment]
I've assigned you! The app isn't currently using any UI library, so as to keep it as simple as possible. Feel free to add any minimal library or build the component yourself, your call! I recommend [shadecn](https://ui.shadcn.com/). Thanks in Advance!❤️❤️

**Comment by AshminJayson** [comment]
I went with [sonner](https://sonner.emilkowal.ski/) to keep it as light weight as possible ⚡

**Comment by marahim20** [comment]
Good choice!
